const express = require("express");
const multer = require("multer");
const cors = require("cors");
const path = require("path");
const fs = require("fs");
const { Octokit } = require("@octokit/rest");
require("dotenv").config();

const { extractText } = require("./src/extract");
const { generatePortfolioData, generateTheme } = require("./src/ai");
const { generateHTML } = require("./src/generator");

const app = express();
const upload = multer({ dest: "uploads/" });

app.use(cors());
app.use(express.json());
app.use(express.static("public"));

// ── In-memory store for generated portfolios ──
// Key: sessionId, Value: { html, name }
const portfolioStore = new Map();

// ── Main generation endpoint ──
app.post("/generate", upload.single("resume"), async (req, res) => {
  const filePath = req.file?.path;
  try {
    if (!req.file) return res.status(400).json({ error: "No file uploaded." });

    const ext = path.extname(req.file.originalname).toLowerCase();
    if (![".pdf", ".docx"].includes(ext)) {
      return res.status(400).json({ error: "Only PDF and DOCX files are supported." });
    }

    const renamedPath = filePath + ext;
    fs.renameSync(filePath, renamedPath);

    const resumeText = await extractText(renamedPath);
    const portfolioData = await generatePortfolioData(resumeText);
    const theme = await generateTheme(portfolioData);
    const html = generateHTML(portfolioData, theme);

    fs.unlinkSync(renamedPath);

    // Store with a simple session ID
    const sessionId = Date.now().toString(36) + Math.random().toString(36).slice(2);
    portfolioStore.set(sessionId, { html, name: portfolioData.name });

    // Clean up old entries after 1 hour
    setTimeout(() => portfolioStore.delete(sessionId), 3600000);

    res.json({ html, name: portfolioData.name, sessionId });

  } catch (err) {
    if (filePath && fs.existsSync(filePath)) fs.unlinkSync(filePath);
    console.error(err);
    res.status(500).json({ error: err.message || "Something went wrong." });
  }
});

// ── GitHub OAuth Step 1: Redirect to GitHub ──
app.get("/auth/github", (req, res) => {
  const { sessionId } = req.query;
  const params = new URLSearchParams({
    client_id: process.env.GITHUB_CLIENT_ID,
    scope: "repo user",
    state: sessionId,
    
  });
  const oauthUrl = `https://github.com/login/oauth/authorize?${params}`;
  const logoutThenAuth = `https://github.com/logout?return_to=${encodeURIComponent(oauthUrl)}`;
  res.redirect(`https://github.com/login/oauth/authorize?${params}`);
});

// ── GitHub OAuth Step 2: Callback from GitHub ──
app.get("/auth/callback", async (req, res) => {
  const { code, state: sessionId } = req.query;

  try {
    // Exchange code for access token
    const tokenRes = await fetch("https://github.com/login/oauth/access_token", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
      },
      body: JSON.stringify({
        client_id: process.env.GITHUB_CLIENT_ID,
        client_secret: process.env.GITHUB_CLIENT_SECRET,
        code,
      }),
    });

    const tokenData = await tokenRes.json();
    const accessToken = tokenData.access_token;

    if (!accessToken) throw new Error("Failed to get access token from GitHub.");

    // Get portfolio HTML from store
    const portfolio = portfolioStore.get(sessionId);
    if (!portfolio) throw new Error("Portfolio session expired. Please generate again.");

    // Get GitHub username
    const octokit = new Octokit({ auth: accessToken });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const username = user.login;
    const repoName = `${username}.github.io`;

    // Create or get repo
    try {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: `${portfolio.name}'s portfolio — generated by Portfol.io`,
        auto_init: false,
        private: false,
      });
    } catch (e) {
      // Repo already exists, that's fine
      if (!e.message.includes("already exists")) throw e;
    }

    // Wait a moment for repo to be ready
    await new Promise(r => setTimeout(r, 1500));

    // Push index.html to repo
    const content = Buffer.from(portfolio.html).toString("base64");

    // Check if file already exists (to get SHA for update)
    let sha;
    try {
      const { data: existing } = await octokit.rest.repos.getContent({
        owner: username,
        repo: repoName,
        path: "index.html",
      });
      sha = existing.sha;
    } catch (e) {
      // File doesn't exist yet, sha stays undefined
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner: username,
      repo: repoName,
      path: "index.html",
      message: "Deploy portfolio via Portfol.io",
      content,
      ...(sha ? { sha } : {}),
    });

    // Enable GitHub Pages
    try {
      await octokit.rest.repos.createPagesSite({
        owner: username,
        repo: repoName,
        source: { branch: "main", path: "/" },
      });
    } catch (e) {
      // Pages might already be enabled
    }

    // Redirect to success page
    const liveUrl = `https://${repoName}`;
    res.redirect(`/?deployed=true&url=${encodeURIComponent(liveUrl)}&name=${encodeURIComponent(portfolio.name)}`);

  } catch (err) {
    console.error(err);
    res.redirect(`/?error=${encodeURIComponent(err.message)}`);
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n  ✦ Portfol.io running at http://localhost:${PORT}\n`);
});