const { Octokit } = require("@octokit/rest");

/**
 * Deploys the generated portfolio HTML directly to the user's GitHub Pages.
 * 
 * @param {Object} params
 * @param {string} params.accessToken - GitHub OAuth access token.
 * @param {string} params.html - The generated HTML string.
 * @param {string} params.portfolioName - The name of the portfolio owner.
 * @returns {Promise<{liveUrl: string}>}
 */
async function deployToGitHubPages({ accessToken, html, portfolioName }) {
  if (!accessToken) throw new Error("Missing GitHub access token.");
  if (!html) throw new Error("No portfolio content to deploy.");

  const octokit = new Octokit({ auth: accessToken });

  // 1. Get authenticated user info
  const { data: user } = await octokit.rest.users.getAuthenticated();
  const username = user.login;
  const repoName = `${username}.github.io`;

  // 2. Create the repository if it doesn't exist
  try {
    await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      description: `${portfolioName}'s portfolio — generated by Portfol.io`,
      auto_init: false,
      private: false, // Must be public for free GitHub Pages hosting
    });
  } catch (e) {
    // If the repo already exists, that's fine, we will just update it.
    if (!e.message.includes("already exists")) {
      throw new Error(`Failed to create repository: ${e.message}`);
    }
  }

  // Wait a short moment for GitHub to initialize the repository metadata
  await new Promise(resolve => setTimeout(resolve, 1500));

  // 3. Prepare the HTML payload in base64
  const content = Buffer.from(html).toString("base64");

  // 4. Retrieve existing file SHA if the index.html already exists
  let sha;
  try {
    const { data: existingFile } = await octokit.rest.repos.getContent({
      owner: username,
      repo: repoName,
      path: "index.html",
    });
    sha = existingFile.sha;
  } catch (e) {
    // If file doesn't exist, sha remains undefined (which triggers creation)
  }

  // 5. Create or update index.html on GitHub
  await octokit.rest.repos.createOrUpdateFileContents({
    owner: username,
    repo: repoName,
    path: "index.html",
    message: "Deploy portfolio via Portfol.io",
    content,
    ...(sha ? { sha } : {}),
  });

  // 6. Enable GitHub Pages on the repository
  try {
    await octokit.rest.repos.createPagesSite({
      owner: username,
      repo: repoName,
      source: { branch: "main", path: "/" },
    });
  } catch (e) {
    // If Pages is already enabled, GitHub might return an error, which we can safely ignore
  }

  return {
    liveUrl: `https://${repoName}`,
    username,
  };
}

module.exports = { deployToGitHubPages };
