// Embedded in every generated page so deploy.js can tell a Portfol.io site
// apart from unrelated content already sitting in a user's username.github.io repo.
const PORTFOLIO_MARKER = "Generated by Portfol.io";

function generateHTML(data, theme, options = {}) {
  const escapeHTML = (str) => {
    if (typeof str !== 'string') return str || '';
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  };

  // Only allow http(s) URLs through into href attributes — blocks
  // javascript:/data: scheme injection from AI-generated (resume-derived) content.
  const safeHref = (url) => {
    if (typeof url !== 'string') return null;
    const trimmed = url.trim();
    if (!/^https?:\/\/[^\s"'<>]+$/i.test(trimmed)) return null;
    return escapeHTML(trimmed);
  };

  const HEX_RE = /^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/;
  const safeColor = (val, fallback) =>
    typeof val === 'string' && HEX_RE.test(val.trim()) ? val.trim() : fallback;

  // ── WCAG contrast helpers ──
  // Backgrounds and the primary color can come from an AI guess or a user's
  // custom palette, neither of which is guaranteed to be readable against the
  // fixed text colors this template used to hardcode. These pick whichever of
  // a light/dark candidate actually meets the AA contrast threshold.
  const hexToRgb = (hex) => {
    const full = hex.length === 4 ? hex.slice(1).split('').map(c => c + c).join('') : hex.slice(1);
    return [0, 2, 4].map(i => parseInt(full.slice(i, i + 2), 16));
  };
  const relativeLuminance = (hex) => {
    const [r, g, b] = hexToRgb(hex).map((v) => {
      const c = v / 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  };
  const contrastRatio = (hexA, hexB) => {
    const lA = relativeLuminance(hexA);
    const lB = relativeLuminance(hexB);
    const lighter = Math.max(lA, lB);
    const darker = Math.min(lA, lB);
    return (lighter + 0.05) / (darker + 0.05);
  };
  const readableTextOn = (bgHex, light, dark, minRatio = 4.5) => {
    const lightRatio = contrastRatio(bgHex, light);
    const darkRatio = contrastRatio(bgHex, dark);
    if (darkRatio >= minRatio && darkRatio >= lightRatio) return dark;
    if (lightRatio >= minRatio) return light;
    return darkRatio >= lightRatio ? dark : light;
  };

  const name = escapeHTML(data.name);
  const tagline = escapeHTML(data.tagline);
  const about = escapeHTML(data.about);
  const cta = escapeHTML(data.cta);

  const skillsHTML = data.skills
    .map(skill => `<span class="skill-tag">${escapeHTML(skill)}</span>`)
    .join("");

  const experienceHTML = data.experience
    .map(
      (exp, i) => `
      <div class="exp-item" style="animation-delay: ${i * 0.1}s">
        <div class="exp-left">
          <span class="exp-period">${escapeHTML(exp.period)}</span>
        </div>
        <div class="exp-right">
          <div class="exp-header">
            <h3 class="exp-role">${escapeHTML(exp.role)}</h3>
            <span class="exp-company">@ ${escapeHTML(exp.company)}</span>
          </div>
          <p class="exp-highlight">${escapeHTML(exp.highlight)}</p>
        </div>
      </div>`
    )
    .join("");

  const projectsHTML = data.projects
    .map(
      (proj, i) => `
      <div class="project-card" style="animation-delay: ${i * 0.15}s">
        <div class="project-inner">
          <div class="project-header">
            <h3 class="project-title">${escapeHTML(proj.title)}</h3>
            ${safeHref(proj.url) ? `<a href="${safeHref(proj.url)}" target="_blank" rel="noopener noreferrer" class="project-link" aria-label="View project">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>
            </a>` : ""}
          </div>
          <p class="project-desc">${escapeHTML(proj.description)}</p>
          <div class="project-tags">
            ${proj.tags.map(tag => `<span class="project-tag">${escapeHTML(tag)}</span>`).join("")}
          </div>
        </div>
      </div>`
    )
    .join("");

  const safeGithub = safeHref(data.github);
  const safeLinkedin = safeHref(data.linkedin);
  const safeWebsite = safeHref(data.website);

  const contactLinks = [
    data.email ? `<a href="mailto:${escapeHTML(data.email)}" class="contact-link">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
      <span>${escapeHTML(data.email)}</span>
    </a>` : "",
    data.phone ? `<a href="tel:${escapeHTML(data.phone.replace(/[^\d+]/g, ''))}" class="contact-link">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.127.96.362 1.903.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.907.338 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
      <span>${escapeHTML(data.phone)}</span>
    </a>` : "",
    safeGithub ? `<a href="${safeGithub}" target="_blank" rel="noopener noreferrer" class="contact-link">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.2c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>
      <span>GitHub</span>
    </a>` : "",
    safeLinkedin ? `<a href="${safeLinkedin}" target="_blank" rel="noopener noreferrer" class="contact-link">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>
      <span>LinkedIn</span>
    </a>` : "",
    safeWebsite ? `<a href="${safeWebsite}" target="_blank" rel="noopener noreferrer" class="contact-link">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>
      <span>Website</span>
    </a>` : "",
  ]
    .filter(Boolean)
    .join("");

  // ── Options: Webpage Title (user-supplied, must be escaped) ──
  const pageTitle = escapeHTML(options.title) || name;

  // ── Options: Favicon — either a short emoji or an http(s) image URL ──
  const getFaviconHref = (favicon) => {
    if (!favicon || typeof favicon !== 'string') return "";
    const trimmed = favicon.trim();
    const isEmoji = /\p{Emoji}/u.test(trimmed) && trimmed.length <= 8;
    if (isEmoji) {
      return `data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>${escapeHTML(trimmed)}</text></svg>`;
    }
    return safeHref(trimmed) || "";
  };
  const faviconHref = getFaviconHref(options.favicon);
  const faviconTag = faviconHref
    ? `<link rel="icon" href="${faviconHref}" />`
    : `<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>✦</text></svg>" />`;

  // ── Options: Color Palette overrides (primary / accent / background) ──
  const customColors = options.colors || {};
  const isDarkColor = (hex) => {
    if (!hex || hex[0] !== '#') return false;
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    const brightness = (r * 299 + g * 587 + b * 114) / 1000;
    return brightness < 128;
  };

  let lightPrimary = safeColor(customColors.primary, theme.light.primary);
  let lightSecondary = theme.light.secondary;
  let lightAccent = safeColor(customColors.accent, theme.light.accent);
  let lightBg = theme.light.background;

  let darkPrimary = safeColor(customColors.primary, theme.dark.primary);
  let darkSecondary = theme.dark.secondary;
  let darkAccent = safeColor(customColors.accent, theme.dark.accent);
  let darkBg = theme.dark.background;

  const safeBackground = safeColor(customColors.background, null);
  if (safeBackground) {
    if (isDarkColor(safeBackground)) {
      darkBg = safeBackground;
    } else {
      lightBg = safeBackground;
    }
  }

  // ── Accessibility: pick body text and CTA-button text colors that actually
  // meet AA contrast against whatever background/primary was resolved above,
  // instead of assuming a fixed near-black/near-white pair always works. ──
  const lightText = readableTextOn(lightBg, '#f3f4f6', '#111111');
  const darkText = readableTextOn(darkBg, '#f3f4f6', '#111111');
  const lightCtaText = readableTextOn(lightPrimary, '#ffffff', '#111111');
  const darkCtaText = readableTextOn(darkPrimary, '#ffffff', '#111111');

  // ── Options: UI Style Overrides ──
  let styleCSS = "";
  if (options.style === "minimalism") {
    styleCSS = `
      /* Minimalism Overrides */
      body {
        --shadow: none !important;
      }
      .project-card, .skill-tag, .theme-toggle, .hero-cta, nav {
        border-radius: 2px !important;
        box-shadow: none !important;
      }
      .project-card:hover {
        transform: translateY(-2px) !important;
        border-color: var(--primary) !important;
      }
    `;
  } else if (options.style === "glassmorphism") {
    styleCSS = `
      /* Glassmorphism Overrides */
      .project-card, nav {
        background: color-mix(in srgb, var(--surface) 40%, transparent) !important;
        backdrop-filter: blur(20px) !important;
        -webkit-backdrop-filter: blur(20px) !important;
        border: 1px solid color-mix(in srgb, var(--border) 50%, transparent) !important;
      }
      .project-card:hover {
        box-shadow: 0 8px 32px var(--shadow) !important;
        background: color-mix(in srgb, var(--surfaceHov) 60%, transparent) !important;
      }
    `;
  } else if (options.style === "brutalism") {
    styleCSS = `
      /* Brutalism Overrides */
      :root {
        --brutal-shadow-color: #000000;
      }
      [data-theme="dark"] {
        --brutal-shadow-color: var(--primary);
      }
      .project-card, .skill-tag, .theme-toggle, .hero-cta, nav {
        border-radius: 0px !important;
        border: 3px solid var(--text) !important;
        box-shadow: 5px 5px 0px var(--brutal-shadow-color) !important;
        background: var(--surface) !important;
      }
      .project-card:hover {
        transform: translate(-2px, -2px) !important;
        box-shadow: 7px 7px 0px var(--brutal-shadow-color) !important;
      }
      .hero-cta:hover, .theme-toggle:hover {
        transform: translate(-1px, -1px) !important;
        box-shadow: 3px 3px 0px var(--brutal-shadow-color) !important;
      }
    `;
  } else if (options.style === "playful") {
    styleCSS = `
      /* Playful Overrides */
      .project-card, .hero-cta {
        border-radius: 20px !important;
      }
      .skill-tag, .theme-toggle {
        border-radius: 100px !important;
      }
      .project-card:hover {
        transform: translateY(-4px) rotate(1deg) !important;
      }
      .hero-cta:hover {
        transform: scale(1.05) !important;
      }
    `;
  }

  return `<!DOCTYPE html>
<!-- ${PORTFOLIO_MARKER} — https://github.com/nh-44/portfolio-gen -->
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${tagline}" />
  <title>${pageTitle}</title>
  ${faviconTag}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(theme.font)}:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
  <style>
    /* ── CSS Variables ── */
    :root {
      --font: '${theme.font}', sans-serif;

      /* Light mode */
      --light-primary:     ${lightPrimary};
      --light-secondary:   ${lightSecondary};
      --light-bg:          ${lightBg};
      --light-surface:     color-mix(in srgb, var(--light-bg) 95%, black);
      --light-surfaceHov:  color-mix(in srgb, var(--light-bg) 90%, black);
      --light-text:        ${lightText};
      --light-textLight:   #666666;
      --light-accent:      ${lightAccent};
      --light-border:      color-mix(in srgb, var(--light-bg) 88%, black);
      --light-shadow:      rgba(0,0,0,0.08);

      /* Dark mode */
      --dark-primary:      ${darkPrimary};
      --dark-secondary:    ${darkSecondary};
      --dark-bg:           ${darkBg};
      --dark-surface:      color-mix(in srgb, var(--dark-bg) 93%, white);
      --dark-surfaceHov:   color-mix(in srgb, var(--dark-bg) 88%, white);
      --dark-text:         ${darkText};
      --dark-textLight:    #9ca3af;
      --dark-accent:       ${darkAccent};
      --dark-border:       color-mix(in srgb, var(--dark-bg) 84%, white);
      --dark-shadow:       rgba(0,0,0,0.3);
    }

    [data-theme="light"] {
      --primary:    var(--light-primary);
      --secondary:  var(--light-secondary);
      --bg:         var(--light-bg);
      --surface:    var(--light-surface);
      --surfaceHov: var(--light-surfaceHov);
      --text:       var(--light-text);
      --textLight:  var(--light-textLight);
      --accent:     var(--light-accent);
      --border:     var(--light-border);
      --shadow:     var(--light-shadow);
    }

    [data-theme="dark"] {
      --primary:    var(--dark-primary);
      --secondary:  var(--dark-secondary);
      --bg:         var(--dark-bg);
      --surface:    var(--dark-surface);
      --surfaceHov: var(--dark-surfaceHov);
      --text:       var(--dark-text);
      --textLight:  var(--dark-textLight);
      --accent:     var(--dark-accent);
      --border:     var(--dark-border);
      --shadow:     var(--dark-shadow);
    }

    /* ── Reset & Base ── */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    html { scroll-behavior: smooth; }

    body {
      font-family: var(--font);
      background: var(--bg);
      color: var(--text);
      line-height: 1.7;
      transition: background 0.3s ease, color 0.3s ease;
      overflow-x: hidden;
    }

    a { color: inherit; text-decoration: none; }

    /* ── Layout ── */
    .container {
      max-width: 860px;
      margin: 0 auto;
      padding: 0 2rem;
    }

    section {
      padding: 5rem 0;
      border-bottom: 1px solid var(--border);
    }

    section:last-of-type { border-bottom: none; }

    .section-label {
      font-size: 0.72rem;
      font-weight: 600;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: var(--primary);
      margin-bottom: 2.5rem;
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }

    .section-label::after {
      content: '';
      flex: 1;
      height: 1px;
      background: var(--border);
    }

    /* ── Nav ── */
    nav {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      z-index: 100;
      padding: 1.25rem 2rem;
      display: flex;
      align-items: center;
      justify-content: space-between;
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
      background: color-mix(in srgb, var(--bg) 85%, transparent);
      border-bottom: 1px solid var(--border);
      transition: background 0.3s ease;
    }

    .nav-name {
      font-weight: 700;
      font-size: 1rem;
      letter-spacing: -0.02em;
    }

    .nav-name span { color: var(--primary); }

    .nav-right {
      display: flex;
      align-items: center;
      gap: 2rem;
    }

    .nav-links {
      display: flex;
      gap: 1.75rem;
      list-style: none;
    }

    .nav-links a {
      font-size: 0.85rem;
      font-weight: 500;
      color: var(--textLight);
      transition: color 0.2s;
    }

    .nav-links a:hover { color: var(--primary); }

    /* ── Theme Toggle ── */
    .theme-toggle {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      border: 1px solid var(--border);
      background: var(--surface);
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s ease;
      color: var(--text);
      flex-shrink: 0;
    }

    .theme-toggle:hover {
      background: var(--surfaceHov);
      border-color: var(--primary);
      color: var(--primary);
    }

    .icon-sun, .icon-moon { transition: opacity 0.2s, transform 0.3s; }
    [data-theme="light"] .icon-moon { display: none; }
    [data-theme="dark"]  .icon-sun  { display: none; }

    /* ── Print Button ── */
    .print-btn {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      border: 1px solid var(--border);
      background: var(--surface);
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s ease;
      color: var(--text);
      flex-shrink: 0;
    }

    .print-btn:hover {
      background: var(--surfaceHov);
      border-color: var(--primary);
      color: var(--primary);
    }

    /* ── Style Overrides Injection ── */
    ${styleCSS}

    /* ── Progress Bar ── */
    #scroll-progress {
      position: fixed;
      top: 0;
      left: 0;
      width: 0%;
      height: 3px;
      background: linear-gradient(90deg, var(--primary), var(--accent));
      z-index: 1001;
      transition: width 0.1s ease-out;
    }

    /* ── Animations ── */
    .gsap-reveal {
      opacity: 0;
      will-change: transform, opacity;
    }

    /* ── Hero ── */
    #hero {
      min-height: 100vh;
      display: flex;
      align-items: center;
      border-bottom: 1px solid var(--border);
      position: relative;
      overflow: hidden;
    }

    .hero-bg {
      position: absolute;
      inset: 0;
      background: radial-gradient(ellipse 80% 60% at 60% 40%, color-mix(in srgb, var(--primary) 12%, transparent), transparent);
      pointer-events: none;
    }

    .hero-content {
      position: relative;
      padding: 8rem 0 5rem;
    }

    .hero-eyebrow {
      font-size: 0.8rem;
      font-weight: 600;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      color: var(--primary);
      margin-bottom: 1.5rem;
    }

    .hero-name {
      font-size: clamp(3rem, 8vw, 5.5rem);
      font-weight: 700;
      line-height: 1.05;
      letter-spacing: -0.03em;
      margin-bottom: 1.25rem;
    }

    .hero-name .highlight { color: var(--primary); }

    .hero-tagline {
      font-size: clamp(1.1rem, 2.5vw, 1.35rem);
      font-weight: 400;
      color: var(--textLight);
      max-width: 540px;
      margin-bottom: 2.5rem;
    }

    .hero-cta {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.85rem 1.75rem;
      background: var(--primary);
      border-radius: 6px;
      font-size: 0.9rem;
      font-weight: 600;
      transition: opacity 0.2s, transform 0.2s, box-shadow 0.2s;
    }

    /* Button text color is computed per-mode against the resolved primary
       color so it stays readable even with an unusual AI or custom palette. */
    [data-theme="light"] .hero-cta { color: ${lightCtaText}; }
    [data-theme="dark"]  .hero-cta { color: ${darkCtaText}; }

    .hero-cta:hover { 
      opacity: 0.92; 
      box-shadow: 0 8px 24px color-mix(in srgb, var(--primary) 35%, transparent);
    }

    /* ── About ── */
    .about-text {
      font-size: 1.15rem;
      line-height: 1.85;
      color: var(--textLight);
      max-width: 680px;
    }

    .about-text strong { color: var(--text); font-weight: 600; }

    /* ── Skills ── */
    .skills-grid {
      display: flex;
      flex-wrap: wrap;
      gap: 0.6rem;
    }

    .skill-tag {
      padding: 0.45rem 1rem;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 100px;
      font-size: 0.82rem;
      font-weight: 500;
      color: var(--textLight);
      transition: all 0.25s cubic-bezier(0.16, 1, 0.3, 1);
      cursor: default;
    }

    .skill-tag:hover {
      background: var(--surfaceHov);
      border-color: var(--primary);
      color: var(--primary);
      transform: translateY(-2px);
      box-shadow: 0 4px 12px var(--shadow);
    }

    /* ── Experience ── */
    .exp-list { display: flex; flex-direction: column; gap: 0; }

    .exp-item {
      display: grid;
      grid-template-columns: 160px 1fr;
      gap: 2rem;
      padding: 2rem 0;
      border-bottom: 1px solid var(--border);
    }

    .exp-item:last-child { border-bottom: none; }

    .exp-period {
      font-size: 0.78rem;
      font-weight: 500;
      color: var(--textLight);
      letter-spacing: 0.02em;
      padding-top: 0.25rem;
    }

    .exp-header {
      display: flex;
      align-items: baseline;
      gap: 0.6rem;
      flex-wrap: wrap;
      margin-bottom: 0.5rem;
    }

    .exp-role {
      font-size: 1rem;
      font-weight: 600;
      color: var(--text);
    }

    .exp-company {
      font-size: 0.88rem;
      color: var(--primary);
      font-weight: 500;
    }

    .exp-highlight {
      font-size: 0.9rem;
      color: var(--textLight);
      line-height: 1.6;
    }

    /* ── Projects ── */
    .projects-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
      gap: 1.25rem;
    }

    .project-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 12px;
      overflow: hidden;
      transition: transform 0.3s cubic-bezier(0.16, 1, 0.3, 1), border-color 0.3s, box-shadow 0.3s;
    }

    .project-card:hover {
      transform: translateY(-6px);
      border-color: var(--primary);
      box-shadow: 0 16px 36px var(--shadow);
    }

    .project-inner { padding: 1.75rem; }

    .project-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 0.75rem;
    }

    .project-title {
      font-size: 1rem;
      font-weight: 600;
    }

    .project-link {
      color: var(--textLight);
      transition: color 0.2s, transform 0.2s;
      display: flex;
    }

    .project-link:hover { color: var(--primary); transform: translate(2px, -2px); }

    .project-desc {
      font-size: 0.875rem;
      color: var(--textLight);
      line-height: 1.65;
      margin-bottom: 1.25rem;
    }

    .project-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 0.4rem;
    }

    .project-tag {
      font-size: 0.72rem;
      font-weight: 600;
      padding: 0.25rem 0.65rem;
      background: color-mix(in srgb, var(--accent) 15%, transparent);
      color: var(--accent);
      border-radius: 4px;
      letter-spacing: 0.02em;
    }

    /* ── Contact ── */
    .contact-intro {
      font-size: 1.1rem;
      color: var(--textLight);
      margin-bottom: 2rem;
      max-width: 480px;
    }

    .contact-links {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .contact-link {
      display: inline-flex;
      align-items: center;
      gap: 0.75rem;
      font-size: 0.95rem;
      font-weight: 500;
      color: var(--textLight);
      transition: color 0.2s, gap 0.2s;
    }

    .contact-link:hover { color: var(--primary); gap: 1rem; }

    /* ── Footer ── */
    footer {
      padding: 2.5rem 0;
      text-align: center;
      font-size: 0.8rem;
      color: var(--textLight);
      border-top: 1px solid var(--border);
    }

    /* ── Responsive ── */
    @media (max-width: 600px) {
      .nav-links { display: none; }
      .exp-item { grid-template-columns: 1fr; gap: 0.25rem; }
      .exp-period { padding-top: 0; }
      .projects-grid { grid-template-columns: 1fr; }
      .hero-name { font-size: 2.8rem; }
    }

    /* ── Scrollbar ── */
    ::-webkit-scrollbar { width: 6px; }
    ::-webkit-scrollbar-track { background: var(--bg); }
    ::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
    ::-webkit-scrollbar-thumb:hover { background: var(--primary); }

    /* ── Print / "Save as PDF" ── */
    @media print {
      /* Force light-mode colors regardless of the active toggle — reliable
         and ink-friendly on paper even if the page was viewed in dark mode. */
      :root {
        --primary: var(--light-primary);
        --secondary: var(--light-secondary);
        --bg: #ffffff;
        --surface: #ffffff;
        --surfaceHov: #ffffff;
        --text: var(--light-text);
        --textLight: var(--light-textLight);
        --accent: var(--light-accent);
        --border: #dddddd;
        --shadow: transparent;
      }
      nav, #scroll-progress, .print-btn, .theme-toggle { display: none !important; }
      html, body { overflow: visible !important; }
      #hero { min-height: 0 !important; padding-top: 1rem !important; }
      section { padding: 1.5rem 0 !important; page-break-inside: avoid; border-bottom: 1px solid #ddd !important; }
      .gsap-reveal { opacity: 1 !important; transform: none !important; }
      .project-card, .skill-tag, .hero-cta { box-shadow: none !important; backdrop-filter: none !important; border: 1px solid #ddd !important; }
      .hero-cta { background: none !important; color: var(--light-text) !important; border: 1px solid #ddd !important; }
      a { text-decoration: underline; }
    }
  </style>
</head>
<body>

  <!-- Scroll Progress Indicator -->
  <div id="scroll-progress"></div>

  <!-- Nav -->
  <nav>
    <div class="nav-name">${name.split(" ")[0]}<span>.</span></div>
    <div class="nav-right">
      <ul class="nav-links">
        <li><a href="#about">About</a></li>
        <li><a href="#experience">Experience</a></li>
        <li><a href="#projects">Projects</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <button class="print-btn magnetic-btn" id="printBtn" aria-label="Save as PDF" title="Save as PDF">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/>
        </svg>
      </button>
      <button class="theme-toggle magnetic-btn" id="themeToggle" aria-label="Toggle dark mode">
        <svg class="icon-sun" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>
        </svg>
        <svg class="icon-moon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
        </svg>
      </button>
    </div>
  </nav>

  <!-- Hero -->
  <section id="hero">
    <div class="hero-bg"></div>
    <div class="container hero-content">
      <p class="hero-eyebrow gsap-reveal">Portfolio</p>
      <h1 class="hero-name gsap-reveal">${(() => { const words = name.split(" "); return words.map((w, i) => i === words.length - 1 ? `<span class="highlight">${w}</span>` : w).join(" "); })()}</h1>
      <p class="hero-tagline gsap-reveal">${tagline}</p>
      <a href="#contact" class="hero-cta gsap-reveal magnetic-btn">
        Get in touch
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
      </a>
    </div>
  </section>

  <!-- About -->
  <section id="about">
    <div class="container">
      <p class="section-label gsap-reveal">About</p>
      <p class="about-text gsap-reveal">${about}</p>
    </div>
  </section>

  <!-- Skills -->
  <section id="skills">
    <div class="container">
      <p class="section-label gsap-reveal">Skills</p>
      <div class="skills-grid">${skillsHTML}</div>
    </div>
  </section>

  <!-- Experience -->
  <section id="experience">
    <div class="container">
      <p class="section-label gsap-reveal">Experience</p>
      <div class="exp-list">${experienceHTML}</div>
    </div>
  </section>

  <!-- Projects -->
  <section id="projects">
    <div class="container">
      <p class="section-label gsap-reveal">Projects</p>
      <div class="projects-grid">${projectsHTML}</div>
    </div>
  </section>

  <!-- Contact -->
  <section id="contact">
    <div class="container">
      <p class="section-label gsap-reveal">Contact</p>
      <p class="contact-intro gsap-reveal">${cta}</p>
      <div class="contact-links">${contactLinks}</div>
    </div>
  </section>

  <footer>
    <div class="container">
      Built with ✦ — ${name}
    </div>
  </footer>

  <!-- Animation & Smooth Scroll Engine Scripts (Lenis & GSAP) -->
  <script src="https://cdn.jsdelivr.net/npm/lenis@1.1.18/dist/lenis.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>

  <script>
    // ── 1. Theme Toggle Management ──
    const toggle = document.getElementById('themeToggle');
    const html = document.documentElement;

    const saved = localStorage.getItem('theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    if (saved) {
      html.setAttribute('data-theme', saved);
    } else if (prefersDark) {
      html.setAttribute('data-theme', 'dark');
    }

    toggle.addEventListener('click', () => {
      const current = html.getAttribute('data-theme');
      const next = current === 'dark' ? 'light' : 'dark';
      html.setAttribute('data-theme', next);
      localStorage.setItem('theme', next);
    });

    // ── 1b. Save as PDF (browser print → "Save as PDF" destination) ──
    document.getElementById('printBtn').addEventListener('click', () => {
      window.print();
    });

    // ── 2. Register GSAP Plugins & Setup Lenis Smooth Scroll ──
    gsap.registerPlugin(ScrollTrigger);

    const lenis = new Lenis({
      duration: 1.2,
      easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
      smoothWheel: true,
    });

    // Sync Lenis scroll updates with GSAP ScrollTrigger
    lenis.on('scroll', (e) => {
      ScrollTrigger.update();
      // Update top progress bar
      const progress = e.scroll / (document.documentElement.scrollHeight - window.innerHeight);
      document.getElementById('scroll-progress').style.width = Math.min(100, Math.max(0, progress * 100)) + '%';
    });

    gsap.ticker.add((time) => {
      lenis.raf(time * 1000);
    });

    gsap.ticker.lagSmoothing(0);

    // ── 3. Smooth Anchor Link Scrolling via Lenis ──
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
          lenis.scrollTo(target, { offset: -70, duration: 1.2 });
        }
      });
    });

    // Respect user reduced-motion preference
    const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    if (!prefersReducedMotion) {
      // ── 4. GSAP Hero Entrance Sequence ──
      const heroTl = gsap.timeline({ defaults: { ease: 'power3.out', duration: 0.9 } });
      heroTl.to('#hero .gsap-reveal', {
        y: 0,
        opacity: 1,
        stagger: 0.15,
        delay: 0.1
      });

      // Subtle parallax effect on hero background
      gsap.to('.hero-bg', {
        yPercent: 30,
        ease: 'none',
        scrollTrigger: {
          trigger: '#hero',
          start: 'top top',
          end: 'bottom top',
          scrub: true
        }
      });

      // ── 5. GSAP Section Reveal Animations ──
      gsap.utils.toArray('section:not(#hero)').forEach((sec) => {
        const reveals = sec.querySelectorAll('.gsap-reveal');
        if (reveals.length > 0) {
          gsap.fromTo(reveals, 
            { y: 35, opacity: 0 }, 
            {
              y: 0,
              opacity: 1,
              duration: 0.8,
              stagger: 0.12,
              ease: 'power3.out',
              scrollTrigger: {
                trigger: sec,
                start: 'top 82%',
                toggleActions: 'play none none reverse'
              }
            }
          );
        }
      });

      // Stagger animation for Skill Tags
      gsap.fromTo('.skill-tag', 
        { scale: 0.8, opacity: 0 }, 
        {
          scale: 1,
          opacity: 1,
          duration: 0.5,
          stagger: 0.04,
          ease: 'back.out(1.5)',
          scrollTrigger: {
            trigger: '#skills',
            start: 'top 80%'
          }
        }
      );

      // Stagger animation for Experience Items
      gsap.fromTo('.exp-item', 
        { y: 30, opacity: 0 }, 
        {
          y: 0,
          opacity: 1,
          duration: 0.7,
          stagger: 0.15,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: '#experience',
            start: 'top 80%'
          }
        }
      );

      // Stagger animation for Project Cards
      gsap.fromTo('.project-card', 
        { y: 40, opacity: 0 }, 
        {
          y: 0,
          opacity: 1,
          duration: 0.7,
          stagger: 0.15,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: '#projects',
            start: 'top 80%'
          }
        }
      );

      // ── 6. Magnetic Buttons Effect ──
      document.querySelectorAll('.magnetic-btn').forEach((btn) => {
        const xTo = gsap.quickTo(btn, "x", { duration: 0.4, ease: "power3.out" });
        const yTo = gsap.quickTo(btn, "y", { duration: 0.4, ease: "power3.out" });

        btn.addEventListener("mousemove", (e) => {
          const { clientX, clientY } = e;
          const { height, width, left, top } = btn.getBoundingClientRect();
          const x = clientX - (left + width / 2);
          const y = clientY - (top + height / 2);
          xTo(x * 0.25);
          yTo(y * 0.25);
        });

        btn.addEventListener("mouseleave", () => {
          xTo(0);
          yTo(0);
        });
      });
    } else {
      // Reveal all content immediately for reduced motion
      gsap.set('.gsap-reveal, .skill-tag, .exp-item, .project-card', { opacity: 1, y: 0, scale: 1 });
    }
  </script>
</body>
</html>`;
}

module.exports = { generateHTML, PORTFOLIO_MARKER };